# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 20

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 30

[[main]]
  name = "Coding"
  url = "#coding"
  weight = 40

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 50

[[main]]
  name = "Projects"
  url = "#slider"
  weight = 60

[[main]]
  name = "Partners"
  url = "#people"
  weight = 70

[[main]]
  name = "Research Exchange"
  url = "#stays"
  weight = 80

[[main]]
  name = "PhD Supervision"
  url = "#phd"
  weight = 90

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 100

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 110

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "https://www.dropbox.com/s/n96h9mma01qf9zt/cv-ojeda.pdf?dl=0"
  weight = 120

